name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Set up a service for the Vite server
      vite:
        image: node:16
        ports:
          - 5173:5173
        options: >-
          --entrypoint /bin/bash
        volumes:
          - .:/app
        command: >
          -c "
          cd /app &&
          npm ci &&
          npm run dev
          "

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Wait for Vite to start
        run: |
          timeout 60 sh -c 'until curl -s http://localhost:5173; do echo waiting for vite...; sleep 2; done'

      - name: Run Playwright tests
        run: npx playwright test